---
title: "Quant"
author: "Wu Wei"
date: "2018-1-25"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))
suppressMessages(library(plyr))

library(sca)

```

## Data Input

```{r}
monthly.deductprofit.sign <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\monthly.deductprofit.sign.csv", 
                                      stringsAsFactors = FALSE)

monthly.industry.data <- 
        read.csv("D:\\MyR\\quantprog\\forAstockbefore20150930\\BAcleandataforNAindustry\\processed.monthly.industry.data.csv", 
                                  stringsAsFactors = FALSE)

```


```{r}
load("D:\\MyR\\quantprog\\forAstockbefore20150930\\BAcleandataforNAindustry\\stockcode")
```


## Data Processing


```{r}
# monthly.industry.data <- monthly.industry.data[,-1]

```


```{r}
monthly.deductprofit.sign <- 
        monthly.deductprofit.sign[monthly.deductprofit.sign$X %in% (paste0("X",stockcode)),]

```



```{r}
nan.code.industry.data <- monthly.industry.data[monthly.industry.data[,2] == "NaN",1]

for(i in 1:length(nan.code.industry.data)){

# for(i in 1:1){

        nan.stock.code <- nan.code.industry.data[i]
        

        nan.code.industry.detail <- monthly.industry.data[monthly.industry.data[,1] == nan.stock.code,]
        

        nan.col.id.industry <- which(nan.code.industry.detail == "NaN")
        
        monthly.deductprofit.sign[monthly.deductprofit.sign[,1] == paste0("X",nan.stock.code), 
                                         nan.col.id.industry] <- "NaN"
                                            

}
```



```{r}
processed.monthly.deductprofit.sign <- monthly.deductprofit.sign[,-ncol(monthly.deductprofit.sign)]
```

```{r}
processed.monthly.deductprofit.sign[is.na(processed.monthly.deductprofit.sign)] <- "NaN"
```


```{r}

write.csv(processed.monthly.deductprofit.sign, 
          "processed.monthly.deductprofit.sign.csv",
          row.names = FALSE)


```

