---
title: "Quant"
author: "Wu Wei"
date: "2018-1-25"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))
suppressMessages(library(plyr))

library(sca)

```

## Data Input

```{r}
monthly.val.lnmv <- read.csv("D:\\MyR\\quantprog\\Acollectdata\\monthly.val.lnmv.csv", 
                                      stringsAsFactors = FALSE)


```


## Data Processing

```{r}
# processed.monthly.holder.sumpcttop5 <- t(monthly.holder.sumpcttop5[,-c(1,ncol(monthly.holder.sumpcttop5))])

processed.monthly.val.lnmv <- monthly.val.lnmv[,-1]


# holder.sumpcttop5.column.names <- monthly.holder.sumpcttop5[,1]
# 
# holder.sumpcttop5.row.names <- colnames(monthly.holder.sumpcttop5)[-c(1, length(monthly.holder.sumpcttop5))]
# 
# 
# processed.monthly.holder.sumpcttop5 <- array(as.numeric(processed.monthly.holder.sumpcttop5),
#                                       dim = dim(processed.monthly.holder.sumpcttop5))

# colnames(processed.monthly.holder.sumpcttop5) <- holder.sumpcttop5.column.names

# row.names(processed.monthly.holder.sumpcttop5) <- holder.sumpcttop5.row.names

row.names(processed.monthly.val.lnmv) <- monthly.val.lnmv[,1]

####delete the data of 2007-12
# processed.monthly.holder.sumpcttop5 <- processed.monthly.holder.sumpcttop5[-1,]

processed.monthly.val.lnmv <- processed.monthly.val.lnmv[,-1]

```

```{r}

# delimitvalue.monthly.holder.sumpcttop5 <- apply(processed.monthly.holder.sumpcttop5, 1, function(x) {
#         median.value <- median(x, na.rm = TRUE)
#         md.sd <- median(abs(x - median.value), na.rm = TRUE)
#         
#         # browser()
#         uplimit <- median.value + 3 * md.sd
#         lowlimit <- median.value - 3 * md.sd
#         x[x > uplimit] <- uplimit
#         x[x < lowlimit] <- lowlimit
#         return(x)
# })

```


```{r}

delimitvalue.monthly.val.lnmv <- apply(processed.monthly.val.lnmv,2, function(x) {
        median.value <- median(x, na.rm = TRUE)
        md.sd <- median(abs(x - median.value), na.rm = TRUE)

        # browser()
        uplimit <- median.value + 3 * md.sd
        lowlimit <- median.value - 3 * md.sd
        x[x > uplimit] <- uplimit
        x[x < lowlimit] <- lowlimit
        return(x)
})

```




```{r}
### 两次去极值

# delimitvalue.monthly.holder.sumpcttop5 <- apply(delimitvalue.monthly.holder.sumpcttop5, 2, function(x) {
#         median.value <- median(x, na.rm = TRUE)
#         md.sd <- median(abs(x - median.value), na.rm = TRUE)
#         
#         # browser()
#         uplimit <- median.value + 3 * md.sd
#         lowlimit <- median.value - 3 * md.sd
#         x[x > uplimit] <- uplimit
#         x[x < lowlimit] <- lowlimit
#         return(x)
# })

```



```{r}
### 两次去极值

delimitvalue.monthly.val.lnmv <- apply(delimitvalue.monthly.val.lnmv, 2, function(x) {
        median.value <- median(x, na.rm = TRUE)
        md.sd <- median(abs(x - median.value), na.rm = TRUE)

        # browser()
        uplimit <- median.value + 3 * md.sd
        lowlimit <- median.value - 3 * md.sd
        x[x > uplimit] <- uplimit
        x[x < lowlimit] <- lowlimit
        return(x)
})

```



```{r}
preProcValues <- preProcess(delimitvalue.monthly.val.lnmv, method = c("center","scale"))

standardlized.monthly.val.lnmv <- predict(preProcValues, delimitvalue.monthly.val.lnmv)

standardlized.monthly.val.lnmv[is.na(standardlized.monthly.val.lnmv)] <- 0
```



```{r}

write.csv(standardlized.monthly.val.lnmv, 
          "D:\\MyR\\quantprog\\Bstandardlizefactor\\standardlized.monthly.val.lnmv.csv")


```

