---
title: "Quant"
author: "Wu Wei"
date: "2018-1-25"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))
suppressMessages(library(plyr))

library(sca)
library(forecast)

```

## Data Input

```{r}

monthly.industry.data <- read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\monthly.industry.data.csv", 
                                  stringsAsFactors = FALSE)

standardlized.monthly.holder.sumpcttop5 <- read.csv(
        "D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.holder.sumpcttop5.csv", 
        stringsAsFactors = FALSE)

standardlized.monthly.pettm.data <- read.csv(
        "D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.pettm.data.csv", 
        stringsAsFactors = FALSE)

standardlized.monthly.tech.turnoverrate60 <- read.csv(
        "D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.tech.turnoverrate60.csv", 
        stringsAsFactors = FALSE)

```

```{r}
monthly.industry.data <- monthly.industry.data[,-1]

```

```{r}
load("comparison.F.hat.g")

load("comparison.Dinv.hat")
```



## Data Processing

```{r}
t.result.F.hat.g <- t(result.F.hat.g)

```

```{r}
comparison.period <- 20

forecast.period <- 1

training.set.endpoint <- nrow(t.result.F.hat.g) - comparison.period

```


```{r}

for(i in 1:comparison.period){

# for(i in 1:1){

# for(i in comparison.period:comparison.period){

        index <- training.set.endpoint + i
                
        factor.forecast <- rbind(apply(head(t.result.F.hat.g, index), 2, function(x) {
                forecast(auto.arima(x), h = forecast.period)$mean
        }))
        
        pettm <- factor.forecast[,"pettm"]
        pettm[pettm > 0] <- 0
        factor.forecast[,"pettm"] <- pettm

        turnoverrate60 <- factor.forecast[,"turnoverrate60"]
        turnoverrate60[turnoverrate60 > 0] <- 0
        factor.forecast[,"turnoverrate60"] <- turnoverrate60

        last.col <- index + 2
        
        mainEffects <- dummyVars(as.formula(paste0(" ~ ", colnames(monthly.industry.data)[last.col])),
                                 data = monthly.industry.data[,c(1,last.col)])
        
        ind.dum <- predict(mainEffects, monthly.industry.data[,c(1, last.col)])
        
        ind.dum <- cbind(ind.dum,
                         abcdefgh.holder.sumpcttop5 = standardlized.monthly.holder.sumpcttop5[,last.col],
                         abcdefgh.pettm = standardlized.monthly.pettm.data[,last.col],
                         abcdefgh.turnoverrate60 = standardlized.monthly.tech.turnoverrate60[,last.col])
        
        stock.return.forecast <- ind.dum %*% t(factor.forecast)
        
        
        row.names(stock.return.forecast) <- monthly.industry.data$code
        return.forecast <- apply(stock.return.forecast, 1, sum)
        
        ordered.return.forecast <- 
                head(return.forecast[order(return.forecast, decreasing = TRUE)],20)        

        if(i == 1){
                result.investion.target <- cbind(names(ordered.return.forecast))
        }else{
                result.investion.target <- cbind(result.investion.target, names(ordered.return.forecast))
        }
        
}

```

```{r}
colnames(result.investion.target) <- row.names(t.result.F.hat.g)[training.set.endpoint + (1:comparison.period)]


```

```{r}
save(result.investion.target, file = "result.investion.target")
```

