---
title: "Quant"
author: "Wu Wei"
date: "2018-6-4"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))
suppressMessages(library(plyr))

library(sca)

```

## Data Input

```{r}
monthly.rating.avg <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\monthly.rating.avg.csv", 
                                      stringsAsFactors = FALSE)

monthly.industry.data <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\monthly.industry.data.csv", 
                                  stringsAsFactors = FALSE)

```

```{r}
load("D:\\MyR\\quantprog\\forAstockbefore20120730\\BAcleandataforNAindustry\\stockcode")
```


## Data Processing
```{r}
##delete data of 20180131

monthly.rating.avg <- monthly.rating.avg[,-ncol(monthly.rating.avg)]


```


```{r}
##所有NA统一设为3-中性评级，然后再针对NA industry的设为NA

monthly.rating.avg[is.na(monthly.rating.avg)] <- 3


```

```{r}
monthly.rating.avg <- monthly.rating.avg[monthly.rating.avg$X %in% stockcode,]

```


```{r}
monthly.industry.data <- monthly.industry.data[,-1]

```

```{r}
monthly.industry.data <- monthly.industry.data[monthly.industry.data$code %in% stockcode,]

```





```{r}
nan.code.industry.data <- monthly.industry.data[monthly.industry.data[,2] == "NaN",1]

for(i in 1:length(nan.code.industry.data)){

# for(i in 1:2){

        nan.stock.code <- nan.code.industry.data[i]
        

        nan.code.industry.detail <- monthly.industry.data[monthly.industry.data[,1] == nan.stock.code,]
        

        nan.col.id.industry <- which(nan.code.industry.detail == "NaN")
        
        monthly.rating.avg[monthly.rating.avg[,1] == nan.stock.code, nan.col.id.industry] <- NA
                                            

}
```



```{r}

write.csv(monthly.rating.avg, 
          "processed.monthly.rating.avg.csv",
          row.names = FALSE)


```

