---
title: "deductprofit_simple_rate_with_sign_factor_efficiency_test"
author: "Wu Wei"
date: "2018-1-25"
output: html_document
---



## Library input


```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))
suppressMessages(library(plyr))

library(sca)

```

## Data Input

```{r}

monthly.industry.data <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\monthly.industry.data.csv", 
                                  stringsAsFactors = FALSE)

standardlized.monthly.price <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.price.csv", 
                                                      stringsAsFactors = FALSE)


standardlized.monthly.deductprofit.simple.rate <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.deductprofit.simple.rate.csv", 
                                                      stringsAsFactors = FALSE)

# processed.monthly.deductprofit.lastperiod.sign <- 
#         read.csv("D:\\MyR\\quantprog\\forallAstock\\BAcleandataforNAindustry\\processed.monthly.deductprofit.lastperiod.sign.csv", 
#                                       stringsAsFactors = FALSE)

processed.monthly.deductprofit.sign <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\BAcleandataforNAindustry\\processed.monthly.deductprofit.sign.csv", 
                                      stringsAsFactors = FALSE)

```

```{r}

monthly.industry.data <- monthly.industry.data[,-1]

row.names(standardlized.monthly.price) <- standardlized.monthly.price[,1]
standardlized.monthly.price <- standardlized.monthly.price[,-1]

standardlized.monthly.price <- as.matrix(standardlized.monthly.price)
```


## Data Processing



```{r}

for(i in 1:nrow(standardlized.monthly.price)){

# for(i in 1:1){

        
        mainEffects.industry <- dummyVars(as.formula(paste0(" ~ ", colnames(monthly.industry.data)[i + 1])),
                                 data = monthly.industry.data[,c(1,(i + 1))])

        ind.dum.industry <- predict(mainEffects.industry, monthly.industry.data[,c(1, (i + 1))])

        ###########
        mainEffects.sign <- dummyVars(as.formula(paste0(" ~ ", colnames(processed.monthly.deductprofit.sign)[i + 1])),
                                          data = processed.monthly.deductprofit.sign[,c(1,(i + 1))])

        ind.dum.sign <- predict(mainEffects.sign, processed.monthly.deductprofit.sign[,c(1, (i + 1))])

        row.names(ind.dum.sign) <- processed.monthly.deductprofit.sign[,1]

        ############
        # mainEffects.lastperiod.sign <- dummyVars(as.formula(paste0(" ~ ", colnames(processed.monthly.deductprofit.lastperiod.sign)[i + 1])),
        #                                   data = processed.monthly.deductprofit.lastperiod.sign[,c(1,(i + 1))])
        # 
        # ind.dum.lastperiod.sign <- predict(mainEffects.lastperiod.sign, processed.monthly.deductprofit.lastperiod.sign[,c(1, (i + 1))])
        # 
        # row.names(ind.dum.lastperiod.sign) <- processed.monthly.deductprofit.lastperiod.sign[,1]

        ##################        
        ind.dum <- cbind(ind.dum.industry, 
                         cbind(ind.dum.sign[,1]),
                         # ind.dum.lastperiod.sign[,1],
                         standardlized.monthly.deductprofit.simple.rate[,(i + 1)])
        
        F.hat.o <- solve(crossprod(ind.dum)) %*% t(ind.dum) %*% t(standardlized.monthly.price)[,i]

        # E.hat.o <- t(rtn)[,i] - ind.dum %*% F.hat.o

        fit <- summary(lm(t(standardlized.monthly.price)[,i] ~ ind.dum - 1))

        if(i == 1){
                result.F.hat.o <- F.hat.o
                # result.E.hat.o <- E.hat.o
                tvalue <- cbind(fit$coefficients[,3])
                
        }else{
                result.F.hat.o <- cbind(result.F.hat.o, F.hat.o)
                # result.E.hat.o <- cbind(result.E.hat.o, E.hat.o)
                tvalue <- cbind(tvalue,fit$coefficients[,3])
        }
}

```


```{r}
# findLinearCombos(ind.dum)
```

## factor efficiency test for deductprofit rate 

```{r}
mean(abs(tail(tvalue, 1)))

t.test(abs(tail(tvalue, 1)))
```

```{r}
mean(abs(tail(tvalue, 1)) > 2)

```

```{r}

t.test(tail(result.F.hat.o, 1))
```

## factor efficiency test for deductprofit sign 

```{r}
mean(abs(tvalue[31,]))

t.test(abs(tvalue[31,]))
```

```{r}
mean(abs(tvalue[31,]) > 2)

```

```{r}

t.test(result.F.hat.o[31,])
```

