---
title: "dividendyield_factor_efficiency_test"
author: "Wu Wei"
date: "2018-1-25"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))
suppressMessages(library(plyr))

library(sca)
library(forecast)
```

## Data Input

```{r}

# monthly.price.data <- 
#         read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\monthly.price.data.csv", 
#                                stringsAsFactors = FALSE)

standardlized.monthly.price <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.price.csv", 
                                                      stringsAsFactors = FALSE)


monthly.industry.data <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\monthly.industry.data.csv", 
                                  stringsAsFactors = FALSE)

standardlized.monthly.dividendyield <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.dividendyield.csv", 
                                             stringsAsFactors = FALSE)

monthly.industry.data <- monthly.industry.data[,-1]

# row.names(monthly.price.data) <- monthly.price.data[,1]
# monthly.price.data <- monthly.price.data[,-1]
# 
# monthly.price.data <- as.matrix(monthly.price.data)
```

```{r}


row.names(standardlized.monthly.price) <- standardlized.monthly.price[,1]
standardlized.monthly.price <- standardlized.monthly.price[,-1]

standardlized.monthly.price <- as.matrix(standardlized.monthly.price)
```


## Data Processing

```{r}
# rm <- matrix(apply(monthly.price.data,2,mean),1)
# rtn <- monthly.price.data - matrix(1,nrow(monthly.price.data),1) %*% rm

rtn <- standardlized.monthly.price
```


```{r}

for(i in 1:nrow(rtn)){

# for(i in 1:1){

        
        mainEffects <- dummyVars(as.formula(paste0(" ~ ", colnames(monthly.industry.data)[i + 1])),
                                 data = monthly.industry.data[,c(1,(i + 1))])

        ind.dum <- predict(mainEffects, monthly.industry.data[,c(1, (i + 1))])

        ind.dum <- cbind(ind.dum, standardlized.monthly.dividendyield[,(i + 1)])
        
        F.hat.o <- solve(crossprod(ind.dum)) %*% t(ind.dum) %*% t(rtn)[,i]

        # E.hat.o <- t(rtn)[,i] - ind.dum %*% F.hat.o

        fit <- summary(lm(t(rtn)[,i] ~ ind.dum - 1))

        if(i == 1){
                result.F.hat.o <- F.hat.o
                # result.E.hat.o <- E.hat.o
                tvalue <- cbind(fit$coefficients[,3])
                
        }else{
                result.F.hat.o <- cbind(result.F.hat.o, F.hat.o)
                # result.E.hat.o <- cbind(result.E.hat.o, E.hat.o)
                tvalue <- cbind(tvalue,fit$coefficients[,3])
        }
}

```

```{r}
colnames(result.F.hat.o) <- row.names(rtn)
```



```{r}
# write.csv(result.F.hat.o,"result.F.csv")
```


```{r}
mean(abs(tail(tvalue, 1)))

t.test(abs(tail(tvalue, 1)))
```

```{r}
mean(abs(tail(tvalue, 1)) > 2)

```

```{r}

t.test(tail(result.F.hat.o, 1))
```

```{r}
ts.f.dividend <- (tail(result.F.hat.o, 1))[1,]
plot(ts.f.dividend,type = "l")
abline(h = 0, col = "red")
auto.arima(ts(ts.f.dividend))
```

