---
title: "dividendyield_factor_efficiency_test_in_seven_factor_model"
author: "Wu Wei"
date: "2018-1-25"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))
suppressMessages(library(plyr))

library(sca)
library(forecast)

```

## Data Input

```{r}


standardlized.monthly.price <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.price.csv", 
                                                      stringsAsFactors = FALSE)


monthly.industry.data <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\monthly.industry.data.csv", 
                                  stringsAsFactors = FALSE)

standardlized.monthly.epttm.data <- 
        read.csv(
        "D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.epttm.data.csv", 
        stringsAsFactors = FALSE)

standardlized.monthly.tech.turnoverrate60 <- 
        read.csv(
        "D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.tech.turnoverrate60.csv", 
        stringsAsFactors = FALSE)

standardlized.monthly.deductprofit.simple.rate <- 
        read.csv(
        "D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.deductprofit.simple.rate.csv", 
        stringsAsFactors = FALSE)

standardlized.monthly.momentum.12month <- 
        read.csv(
        "D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.momentum.12month.csv", 
        stringsAsFactors = FALSE)

standardlized.monthly.momentum.3month <- 
        read.csv(
        "D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.momentum.3month.csv", 
        stringsAsFactors = FALSE)


standardlized.monthly.val.lnmv <- 
        read.csv(
        "D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.val.lnmv.csv", 
        stringsAsFactors = FALSE)

standardlized.monthly.dividendyield <- 
        read.csv(
        "D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.dividendyield.csv", 
        stringsAsFactors = FALSE)

```

```{r}
monthly.industry.data <- monthly.industry.data[,-1]

```

```{r}
row.names(standardlized.monthly.price) <- standardlized.monthly.price[,1]
standardlized.monthly.price <- standardlized.monthly.price[,-1]

standardlized.monthly.price <- as.matrix(standardlized.monthly.price)
```



## Data Processing

```{r}
rtn <- standardlized.monthly.price
```

```{r}
comparison.period <- 20

### let the starting point to be same in different forecast.period
training.set.endpoint <- nrow(rtn) - comparison.period - 4
```


```{r}

result.r.square.ols <- numeric(training.set.endpoint)

result.adj.r.square.ols <- numeric(training.set.endpoint)


sample.length <- nrow(monthly.industry.data)

for(i in 1:training.set.endpoint){

# for(i in 1:1){

        
        mainEffects <- dummyVars(as.formula(paste0(" ~ ", colnames(monthly.industry.data)[i + 1])),
                                 data = monthly.industry.data[,c(1,(i + 1))])

        ind.dum <- predict(mainEffects, monthly.industry.data[,c(1, (i + 1))])

        ind.dum <- cbind(ind.dum,
                         abcdefgh.epttm = standardlized.monthly.epttm.data[,(i + 1)],
                         abcdefgh.turnoverrate60 = standardlized.monthly.tech.turnoverrate60[,(i + 1)],
                         abcdefgh.deductprofit.simple.rate = standardlized.monthly.deductprofit.simple.rate[,(i + 1)],
                         abcdefgh.momentum.12month = standardlized.monthly.momentum.12month[,(i + 1)],
                         abcdefgh.momentum.3month = standardlized.monthly.momentum.3month[,(i + 1)],
                         abcdefgh.val.lnmv = standardlized.monthly.val.lnmv[,(i + 1)],
                         abcdefgh.dividendyield = standardlized.monthly.dividendyield[,(i + 1)])
        
        F.hat.o <- solve(crossprod(ind.dum)) %*% t(ind.dum) %*% t(rtn)[,i]

        E.hat.o <- t(rtn)[,i] - ind.dum %*% F.hat.o
        
        result.r.square.ols[i] <- 1 - var(E.hat.o) / var(t(rtn)[,i])
        
        result.adj.r.square.ols[i] <- 1 - (var(E.hat.o) * (sample.length - 1)) / 
                (var(t(rtn)[,i])* (sample.length - ncol(ind.dum) - 1))

        
        if(i == 1){
                result.F.hat.o <- F.hat.o
                result.E.hat.o <- E.hat.o
                
        }else{
                result.F.hat.o <- cbind(result.F.hat.o, F.hat.o)
                result.E.hat.o <- cbind(result.E.hat.o, E.hat.o)
        }
}

```

```{r}
median(result.r.square.ols)

median(result.adj.r.square.ols)
```


```{r}
current.row.names <- row.names(result.F.hat.o)
row.names(result.F.hat.o) <- substr(current.row.names, 10, nchar(current.row.names))

colnames(result.F.hat.o) <- colnames(t(rtn))[1:training.set.endpoint]


```

```{r}
result.E.hat.o[result.E.hat.o == 0] <- NA

diagD.hat.o <- apply(result.E.hat.o,1,var,na.rm = TRUE)

md.diagD.hat.o <- median(diagD.hat.o, na.rm = TRUE)

diagD.hat.o[is.na(diagD.hat.o)] <- md.diagD.hat.o


```

```{r}
reciprocal.diagD.hat.o <- diagD.hat.o^(-1)
```


```{r}
                
median.value <- median(reciprocal.diagD.hat.o, na.rm = TRUE)
md.sd <- median(abs(reciprocal.diagD.hat.o - median.value), na.rm = TRUE)

# browser()

if(md.sd == 0){
        md.sd <- sd(reciprocal.diagD.hat.o)
}

uplimit <- median.value + 5 * md.sd
lowlimit <- median.value - 5 * md.sd
reciprocal.diagD.hat.o[reciprocal.diagD.hat.o > uplimit] <- uplimit
reciprocal.diagD.hat.o[reciprocal.diagD.hat.o < lowlimit] <- lowlimit
```




```{r}

Dinv.hat <- diag(reciprocal.diagD.hat.o)

```

```{r}
# save(Dinv.hat, file = "comparison.Dinv.hat")
```

```{r}
# load(file = "comparison.Dinv.hat")
```


```{r}
result.r.square.gls <- numeric(training.set.endpoint + comparison.period)

result.adj.r.square.gls <- numeric(training.set.endpoint + comparison.period)

for(i in 1:(training.set.endpoint + comparison.period)){


# for(i in 1:1){

        
        mainEffects <- dummyVars(as.formula(paste0(" ~ ", colnames(monthly.industry.data)[i + 1])),
                                 data = monthly.industry.data[,c(1,(i + 1))])

        ind.dum <- predict(mainEffects, monthly.industry.data[,c(1, (i + 1))])

        ind.dum <- cbind(ind.dum,
                         abcdefgh.epttm = standardlized.monthly.epttm.data[,(i + 1)],
                         abcdefgh.turnoverrate60 = standardlized.monthly.tech.turnoverrate60[,(i + 1)],
                         abcdefgh.deductprofit.simple.rate = standardlized.monthly.deductprofit.simple.rate[,(i + 1)],
                         abcdefgh.momentum.12month = standardlized.monthly.momentum.12month[,(i + 1)],
                         abcdefgh.momentum.3month = standardlized.monthly.momentum.3month[,(i + 1)],
                         abcdefgh.val.lnmv = standardlized.monthly.val.lnmv[,(i + 1)],
                         abcdefgh.dividendyield = standardlized.monthly.dividendyield[,(i + 1)]
                         )
        
        
        Hmtx <- solve(t(ind.dum) %*% Dinv.hat %*% ind.dum) %*% t(ind.dum) %*% Dinv.hat
                
        F.hat.g <- Hmtx %*%  t(rtn)[,i]

        E.hat.g <- t(rtn)[,i] - ind.dum %*% F.hat.g

        result.r.square.gls[i] <- 1 - var(E.hat.g) / var(t(rtn)[,i])

        result.adj.r.square.gls[i] <- 1 - (var(E.hat.g) * (sample.length - 1)) / 
                (var(t(rtn)[,i])* (sample.length - ncol(ind.dum) - 1))
        
        if(i == 1){
                result.F.hat.g <- F.hat.g
                # result.E.hat.g <- E.hat.g
        }else{
                result.F.hat.g <- cbind(result.F.hat.g, F.hat.g)
                # result.E.hat.g <- cbind(result.E.hat.g, E.hat.g)
        }
}


```

```{r}
median(result.r.square.gls)

median(result.adj.r.square.gls)
```


```{r}
current.row.names <- row.names(result.F.hat.g)
row.names(result.F.hat.g) <- substr(current.row.names, 10, nchar(current.row.names))

colnames(result.F.hat.g) <- colnames(t(rtn))[1:(training.set.endpoint + comparison.period)]


```

```{r}
# save(result.F.hat.g, file = "comparison.F.hat.g")
```

```{r}
write.csv(result.F.hat.g, file = "result.F.dividend.csv")
```

```{r}
t.test(tail(result.F.hat.g["dividendyield",], 24))
```

```{r}
t.test(result.F.hat.g["dividendyield",])

# forecast(ets(result.F.hat.g["dividendyield",]), h = 2)
# 
# forecast(ets(head(result.F.hat.g["dividendyield",], 120)), h = 2)

# auto.arima(result.F.hat.g["dividendyield",])
```


```{r}
plot(result.F.hat.g["dividendyield",], type = "l")
abline(h=0,col = "red")
```

