---
title: "Quant"
author: "Wu Wei"
date: "2018-1-25"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))
suppressMessages(library(plyr))

library(sca)
library(forecast)
```

## Data Input

```{r}

monthly.price.data <- read.csv("D:\\MyR\\quantprog\\Acollectdata\\monthly.price.data.csv", 
                               stringsAsFactors = FALSE)

monthly.industry.data <- read.csv("D:\\MyR\\quantprog\\Acollectdata\\monthly.industry.data.csv", 
                                  stringsAsFactors = FALSE)

standardlized.monthly.holder.sumpcttop5 <- read.csv(
        "D:\\MyR\\quantprog\\Bstandardlizefactor\\standardlized.monthly.holder.sumpcttop5.csv", 
        stringsAsFactors = FALSE)

standardlized.monthly.pettm.data <- read.csv(
        "D:\\MyR\\quantprog\\Bstandardlizefactor\\standardlized.monthly.pettm.data.csv", 
        stringsAsFactors = FALSE)

standardlized.monthly.tech.turnoverrate60 <- read.csv(
        "D:\\MyR\\quantprog\\Bstandardlizefactor\\standardlized.monthly.tech.turnoverrate60.csv", 
        stringsAsFactors = FALSE)


hushen300.price <- read.csv("D:\\MyR\\quantprog\\Acollectdata\\hushen300.monthly.price.csv",
                               stringsAsFactors = FALSE)

```

```{r}
monthly.industry.data <- monthly.industry.data[,-1]

row.names(monthly.price.data) <- monthly.price.data[,1]
monthly.price.data <- monthly.price.data[,-1]

monthly.price.data <- as.matrix(monthly.price.data)
```



## Data Processing

```{r}
rm <- matrix(apply(monthly.price.data,2,mean),1)
rtn <- monthly.price.data - matrix(1,nrow(monthly.price.data),1) %*% rm


```

```{r}
comparison.period <- 20

forecast.period <- 1

training.set.endpoint <- nrow(rtn) - comparison.period - forecast.period
```


```{r}

for(i in 1:training.set.endpoint){

# for(i in 1:1){

        
        mainEffects <- dummyVars(as.formula(paste0(" ~ ", colnames(monthly.industry.data)[i + 1])),
                                 data = monthly.industry.data[,c(1,(i + 1))])

        ind.dum <- predict(mainEffects, monthly.industry.data[,c(1, (i + 1))])

        ind.dum <- cbind(ind.dum,
                         abcdefgh.holder.sumpcttop5 = standardlized.monthly.holder.sumpcttop5[,(i + 1)],
                         abcdefgh.pettm = standardlized.monthly.pettm.data[,(i + 1)],
                         abcdefgh.turnoverrate60 = standardlized.monthly.tech.turnoverrate60[,(i + 1)])
        
        F.hat.o <- solve(crossprod(ind.dum)) %*% t(ind.dum) %*% t(rtn)[,i]

        E.hat.o <- t(rtn)[,i] - ind.dum %*% F.hat.o

        if(i == 1){
                result.F.hat.o <- F.hat.o
                result.E.hat.o <- E.hat.o
        }else{
                result.F.hat.o <- cbind(result.F.hat.o, F.hat.o)
                result.E.hat.o <- cbind(result.E.hat.o, E.hat.o)
        }
}

```


```{r}
current.row.names <- row.names(result.F.hat.o)
row.names(result.F.hat.o) <- substr(current.row.names, 10, nchar(current.row.names))

colnames(result.F.hat.o) <- colnames(t(rtn))[1:training.set.endpoint]


```

```{r}
diagD.hat.o <- apply(result.E.hat.o,1,var)

Dinv.hat <- diag(diagD.hat.o^(-1))

```

```{r}
# save(Dinv.hat, file = "comparison.Dinv.hat")
```

```{r}
# load(file = "comparison.Dinv.hat")
```


```{r}

for(i in 1:(training.set.endpoint + comparison.period)){

# for(i in 1:1){

        
        mainEffects <- dummyVars(as.formula(paste0(" ~ ", colnames(monthly.industry.data)[i + 1])),
                                 data = monthly.industry.data[,c(1,(i + 1))])

        ind.dum <- predict(mainEffects, monthly.industry.data[,c(1, (i + 1))])

        ind.dum <- cbind(ind.dum,
                         abcdefgh.holder.sumpcttop5 = standardlized.monthly.holder.sumpcttop5[,(i + 1)],
                         abcdefgh.pettm = standardlized.monthly.pettm.data[,(i + 1)],
                         abcdefgh.turnoverrate60 = standardlized.monthly.tech.turnoverrate60[,(i + 1)])
        
        
        Hmtx <- solve(t(ind.dum) %*% Dinv.hat %*% ind.dum) %*% t(ind.dum) %*% Dinv.hat
                
        F.hat.g <- Hmtx %*%  t(rtn)[,i]

        # E.hat.g <- t(rtn)[,i] - ind.dum %*% F.hat.g

        if(i == 1){
                result.F.hat.g <- F.hat.g
                # result.E.hat.g <- E.hat.g
        }else{
                result.F.hat.g <- cbind(result.F.hat.g, F.hat.g)
                # result.E.hat.g <- cbind(result.E.hat.g, E.hat.g)
        }
}

```

```{r}
current.row.names <- row.names(result.F.hat.g)
row.names(result.F.hat.g) <- substr(current.row.names, 10, nchar(current.row.names))

colnames(result.F.hat.g) <- colnames(t(rtn))[1:(training.set.endpoint + comparison.period)]


```

```{r}
# save(result.F.hat.g, file = "comparison.F.hat.g")
```


## Investion Target Selection

```{r}
t.result.F.hat.g <- t(result.F.hat.g)

```

```{r}
comparison.period <- 20

forecast.period <- 1

training.set.endpoint <- nrow(t.result.F.hat.g) - comparison.period

```


```{r}

for(i in 1:comparison.period){
# for(i in 1:1){

        index <- training.set.endpoint + i
                
        factor.forecast <- apply(head(t.result.F.hat.g, index), 2, function(x) {
                forecast(auto.arima(x), h = forecast.period)$mean
        })
        
        last.col <- index + 1
        
        mainEffects <- dummyVars(as.formula(paste0(" ~ ", colnames(monthly.industry.data)[last.col])),
                                 data = monthly.industry.data[,c(1,last.col)])
        
        ind.dum <- predict(mainEffects, monthly.industry.data[,c(1, last.col)])
        
        ind.dum <- cbind(ind.dum,
                         abcdefgh.holder.sumpcttop5 = standardlized.monthly.holder.sumpcttop5[,last.col],
                         abcdefgh.pettm = standardlized.monthly.pettm.data[,last.col],
                         abcdefgh.turnoverrate60 = standardlized.monthly.tech.turnoverrate60[,last.col])
        
        if(is.null(dim(factor.forecast))){
                        stock.return.forecast <- ind.dum %*% cbind(factor.forecast)
        }else{
                        stock.return.forecast <- ind.dum %*% t(factor.forecast)
        }

        
        row.names(stock.return.forecast) <- monthly.industry.data$code
        return.forecast <- apply(stock.return.forecast, 1, sum)
        
        ordered.return.forecast <- 
                head(return.forecast[order(return.forecast, decreasing = TRUE)],20)        

        if(i == 1){
                result.investion.target <- names(ordered.return.forecast)
        }else{
                result.investion.target <- cbind(result.investion.target, names(ordered.return.forecast))
        }
        
}

```

```{r}
colnames(result.investion.target) <- row.names(t.result.F.hat.g)[training.set.endpoint + (1:comparison.period)]


```

```{r}
# save(result.investion.target, file = "result.investion.target")
```


## Comparison with hushen300


```{r}
selected.stocks.actual.return <- numeric(comparison.period)
hushen300.return <- numeric(comparison.period)

for(i in 1:comparison.period){


        date.name <- colnames(result.investion.target)[i]        
        index <- which(row.names(monthly.price.data) == date.name)
        
        selected.stocks.actual.return[i] <- sum(mean(unlist(monthly.price.data[(index + (1:forecast.period)),
                                           colnames(monthly.price.data) %in% paste0("X",result.investion.target[,i])])))

        hushen300.return[i] <- sum(hushen300.price[(index + (1:forecast.period)), 2])
}

```

```{r}
names(selected.stocks.actual.return) <- colnames(result.investion.target)
names(hushen300.return) <- colnames(result.investion.target)
```

```{r}
mean(selected.stocks.actual.return > hushen300.return)
```

