---
title: "Multi_colinearity_test"
author: "Wu Wei"
date: "2018-6-5"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))
suppressMessages(library(plyr))

library(sca)

```

## Data Input

```{r}

standardlized.monthly.holder.sumpcttop5 <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.holder.sumpcttop5.csv", 
                                                    stringsAsFactors = FALSE)

standardlized.monthly.epttm.data <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.epttm.data.csv", 
                                                    stringsAsFactors = FALSE)

standardlized.monthly.risk.variance60 <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.risk.variance60.csv", 
                                                    stringsAsFactors = FALSE)

standardlized.monthly.roe.data <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.roe.data.csv", 
                                                    stringsAsFactors = FALSE)

standardlized.monthly.tech.turnoverrate60 <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.tech.turnoverrate60.csv", 
                                                    stringsAsFactors = FALSE)


```

```{r}

standardlized.monthly.val.lnmv <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.val.lnmv.csv", 
                                                    stringsAsFactors = FALSE)


standardlized.monthly.rating.avg <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.rating.avg.csv", 
                                                    stringsAsFactors = FALSE)


standardlized.monthly.momentum.12month <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.momentum.12month.csv", 
                                                    stringsAsFactors = FALSE)

standardlized.monthly.momentum.6month <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.momentum.6month.csv", 
                                                    stringsAsFactors = FALSE)

standardlized.monthly.momentum.3month <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.momentum.3month.csv", 
                                                    stringsAsFactors = FALSE)

```

```{r}

standardlized.monthly.deductprofit.simple.rate <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.deductprofit.simple.rate.csv", 
                                                    stringsAsFactors = FALSE)

standardlized.monthly.dividendyield <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Bstandardlizefactor\\standardlized.monthly.dividendyield.csv", 
                                                    stringsAsFactors = FALSE)

```



## Data Processing

```{r}
month.length <- ncol(standardlized.monthly.holder.sumpcttop5) - 1

cor.table.array <- array(NA, dim = c(12,12,month.length))

zero.ind <- array(c(1:12,1:12),dim = c(12,2))

for(i in 1:month.length){
# for(i in 1:1){
        
        var.table <- cbind(standardlized.monthly.holder.sumpcttop5[,(i + 1)],
              standardlized.monthly.epttm.data[,(i + 1)],
              standardlized.monthly.risk.variance60[,(i + 1)],
              standardlized.monthly.roe.data[,(i + 1)],
              standardlized.monthly.tech.turnoverrate60[,(i + 1)],
              standardlized.monthly.val.lnmv[,(i + 1)],
              standardlized.monthly.rating.avg[,(i + 1)],
              standardlized.monthly.momentum.12month[,(i + 1)],
              standardlized.monthly.momentum.6month[,(i + 1)],
              standardlized.monthly.momentum.3month[,(i + 1)],
              standardlized.monthly.deductprofit.simple.rate[,(i + 1)],
              standardlized.monthly.dividendyield[,(i + 1)])
        

        cor.result <- cor(var.table)
        
        cor.result[zero.ind] <- 0
        
        cor.table.array[,,i] <- cor.result
}


```

```{r}
data.frame(name = c("holder.sumpcttop5",
              "epttm.data",
              "risk.variance60",
              "roe.data",
              "tech.turnoverrate60",
              "val.lnmv",
              "rating.avg",
              "momentum.12month",
              "momentum.6month",
              "momentum.3month",
              "deductprofit.simple.rate",
              "dividendyield")
)
```


```{r}


mean.test.result <- apply(cor.table.array, c(1,2), function(x) mean(abs(x)))
which(mean.test.result > 0.6, arr.ind = TRUE)

median.test.result <- apply(cor.table.array, c(1,2), function(x) median(abs(x)))
which(median.test.result > 0.6, arr.ind = TRUE)

t.test(abs(cor.table.array[2,4,]))

t.test(abs(cor.table.array[3,5,]))

t.test(abs(cor.table.array[8,9,]))

t.test(abs(cor.table.array[9,10,]))

t.test(abs(cor.table.array[8,10,]))

t.test(abs(cor.table.array[4,12,]))

t.test(abs(cor.table.array[2,12,]))
```

