---
title: "Quant"
author: "Wu Wei"
date: "2018-1-25"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))


```

## Data Input

```{r}
monthly.deductprofit.ttm <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\originaldata\\originaldata.deductprofit.rate.csv", 
                                      stringsAsFactors = FALSE)


```


## Data process
```{r}
row.names(monthly.deductprofit.ttm) <- monthly.deductprofit.ttm$X

monthly.deductprofit.ttm <- monthly.deductprofit.ttm[,-1]

```

```{r}
monthly.deductprofit.ttm[is.na(monthly.deductprofit.ttm)] <- 0

deductprofit.rate.numerator <- diff(ts(monthly.deductprofit.ttm))

deductprofit.rate.denominator <- abs(monthly.deductprofit.ttm[-nrow(monthly.deductprofit.ttm),])
```

```{r}

monthly.deductprofit.simple.rate <- as.matrix(deductprofit.rate.numerator) / as.matrix(deductprofit.rate.denominator)
```

```{r}

row.names(monthly.deductprofit.simple.rate) <- row.names(monthly.deductprofit.ttm)[-1]
        
```

```{r}

monthly.deductprofit.simple.rate <- monthly.deductprofit.simple.rate[-(1:3),]

```

```{r}

monthly.deductprofit.simple.rate[is.nan(monthly.deductprofit.simple.rate)] <- 0 

monthly.deductprofit.simple.rate[is.infinite(monthly.deductprofit.simple.rate)] <- 0 

```

```{r}
monthly.deductprofit.simple.rate <- apply(monthly.deductprofit.simple.rate, 2 , function(x){
        for(i in 1:(length(x) - 1)){
                if (x[i + 1] == 0 && x[i] != 0) x[i + 1] <- x[i]
        }
        
        return(x)
})
```

```{r}

monthly.deductprofit.simple.rate <- monthly.deductprofit.simple.rate[-(1:2),]

```



```{r}

write.csv(t(monthly.deductprofit.simple.rate), "monthly.deductprofit.simple.rate.csv")
```


