---
title: "Quant"
author: "Wu Wei"
date: "2018-1-25"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))


```

## Data Input

```{r}
monthly.deductprofit.ttm <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\originaldata\\originaldata.deductprofit.rate.csv", 
                                      stringsAsFactors = FALSE)


```


## Data process
```{r}
row.names(monthly.deductprofit.ttm) <- monthly.deductprofit.ttm$X

monthly.deductprofit.ttm <- monthly.deductprofit.ttm[,-1]

```


```{r}
monthly.deductprofit.ttm[is.na(monthly.deductprofit.ttm)] <- 0

```

```{r}
monthly.deductprofit.lastperiod.sign <- apply(monthly.deductprofit.ttm, 2 , function(x){
        for(i in length(x):5){
                # browser()
                index <- which(x[1:(i-1)] != x[i])
                if(length(index) > 0){

                        x[i] <- x[max(index)]                        
                }

        }
        
        return(x)
})
```

```{r}

monthly.deductprofit.lastperiod.sign[monthly.deductprofit.lastperiod.sign == 0] <- NA
```

```{r}

monthly.deductprofit.lastperiod.sign[monthly.deductprofit.lastperiod.sign >= 0] <- "profit"
monthly.deductprofit.lastperiod.sign[monthly.deductprofit.lastperiod.sign < 0] <- "loss"
```

```{r}
monthly.deductprofit.lastperiod.sign <- monthly.deductprofit.lastperiod.sign[-(1:6),]
```


```{r}

write.csv(t(monthly.deductprofit.lastperiod.sign), "monthly.deductprofit.lastperiod.sign.csv")
```


