---
title: "Collect new data about price and industry"
author: "Wu Wei"
date: "2018-5-29"
output: html_document
---



## Library input
```{r}
rm(list = ls())

suppressMessages(library(lubridate))
suppressMessages(library(caret))

suppressMessages(library(WindR))
w.start()

```

## Data Input

```{r}
w_wset_data<-w.wset('sectorconstituent','date=2018-01-25;sectorid=a001010100000000')

stockcode <- w_wset_data$Data$wind_code

```



```{r}

w_tdays_data<-w.tdays("2017-12-1","2018-5-29","Period=M")

tdate <- as.character(w_tdays_data$Data$DATETIME)

tdate <- gsub("-","",tdate)
```

```{r}

for(i in 1:length(tdate)){


       tradedatepara <- paste0('tradeDate=', tdate[i])
       

       ### the price may be NaN if the IPO data is later than 2013-12-01
       w_wss_price <- w.wss( stockcode,
                           'close',
                           tradedatepara,
                           'priceAdj=F',
                           'cycle=D')
       
       w_wss_industry <- w.wss(stockcode,
                              'industry_citic',
                              tradedatepara,
                              'industryType=1')
       
        if(i == 1){
                monthly.price.data <- w_wss_price$Data

                monthly.industry.data <- w_wss_industry$Data
        }else{
                monthly.price.data <- cbind(monthly.price.data,
                                            w_wss_price$Data$CLOSE)
                
                monthly.industry.data <- cbind(monthly.industry.data,
                                           w_wss_industry$Data$INDUSTRY_CITIC)
        }


}
```


```{r}
####backup
monthly.industry.data.backup <- monthly.industry.data
monthly.price.data.backup <- monthly.price.data

```


```{r}
monthly.industry.data <- monthly.industry.data.backup
monthly.price.data <- monthly.price.data.backup
```



```{r}
colnames(monthly.price.data) <- c("code", paste0("d",tdate))
row.names(monthly.price.data) <- monthly.price.data[,"code"]

colnames(monthly.industry.data) <- c("code", paste0("d",tdate))
```


```{r}
nan.code.industry.data <- monthly.industry.data[monthly.industry.data[,2] == "NaN",1]

for(i in 1:length(nan.code.industry.data)){

# for(i in 1:2){
# i <- 1
        nan.stock.code <- nan.code.industry.data[i]

        # print(nan.stock.code)

        # nan.stock.code <- "001965.SZ"

        nan.code.industry.detail <- monthly.industry.data[monthly.industry.data[,1] == nan.stock.code,]
        nan.code.price.detail <- monthly.price.data[monthly.price.data[,1] == nan.stock.code,]

        nan.col.id.industry <- which(nan.code.industry.detail == "NaN")
        nan.col.id.price <- which(nan.code.price.detail == "NaN")

        nan.col.id.industry.minus.price <- setdiff(nan.col.id.industry, nan.col.id.price)
        if(length(nan.col.id.industry.minus.price) > 0){
                first.industry.col.id <- intersect(which(colnames(nan.code.industry.detail) != "code"),
                              which(nan.code.industry.detail != "NaN"))

                if(length(first.industry.col.id) > 0){

                        first.industry.col.id <- min(first.industry.col.id)
                        first.industry.name <- nan.code.industry.detail[1,first.industry.col.id]

                        nan.code.industry.detail[1,nan.col.id.industry.minus.price] <- as.character(first.industry.name)
                        monthly.industry.data[monthly.industry.data[,1] == nan.stock.code,] <- nan.code.industry.detail
                }


        }
}
```



```{r}
# monthly.price.data <- monthly.price.data[,-1]
# monthly.price.data <- t(monthly.price.data)
# 
# monthly.price.data <- diff(log(monthly.price.data))

# monthly.price.data[is.nan(monthly.price.data)] <- 0
```



```{r}

# monthly.industry.data <- monthly.industry.data[,-2]
```

```{r}
old.monthly.industry.data <- 
        read.csv("D:\\MyR\\quantprog\\forallAstock\\Acollectdata\\monthly.industry.data.csv", 
                                  stringsAsFactors = FALSE)
```

```{r}
new.monthly.industry.data <- cbind(old.monthly.industry.data, monthly.industry.data[,-c(1:2)]) 
```


```{r}

write.csv(new.monthly.industry.data[,-1], "monthly.industry.data.csv")

```


